# Generated by Django 5.1.6 on 2025-02-09 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="recent_searches",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
